import jenkins.model.*
jenkins = Jenkins.instance
	pipeline {
		agent any
		stage('build'){
			steps {
				echo 'Building...'
			}
		}
		stage('test'){
			steps {
				echo 'Testing...'
			}
		}
		

	}
