#!C:\\Users\\rbangaru\\Downloads\\groovy-2.5.5\bin
//import jenkins.model.*
//jenkins = Jenkins.instance
    pipeline {
        agent any
            stages {
               stage('build'){
                 steps {
                   echo 'Building...'
                }
            }
        }
    }
