	
	pipeline {
		agent any
		stage('build'){
			steps {
				echo 'Building...'
			}
		}
		stage('test'){
			steps {
				echo 'Testing...'
			}
		}
		stage('install'){
			steps {
				echo 'Installing...'
			}
		}
		stage('deploy'){
			steps {
				echo 'Deploying...'
			}
		}

	}
